export const RIEW_NEW_SESSION = 'RIEW_NEW_SESSION';
export const TYPES = {
  RIEW: 'RIEW',
  CHANNEL: 'CHANNEL',
  ROUTINE: 'ROUTINE',
  STATE: 'STATE',
  BUFFER_TYPES: {
    FIXED: 'FIXED',
    SLIDING: 'SLIDING',
    DROPPING: 'DROPPING',
  },
  UNRECOGNIZED: 'UNRECOGNIZED',
};
